"""stage 3 task and backup foundation

Revision ID: bc554b1b4366
Revises: 0001_stage0_app_meta
Create Date: 2026-09-22 12:34:39.535892
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'bc554b1b4366'
down_revision: Union[str, Sequence[str], None] = '0001_stage0_app_meta'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('setting_key', sa.String(length=100), nullable=False),
    sa.Column('setting_value_json', sa.JSON(), nullable=True),
    sa.Column('setting_schema_version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('setting_key')
    )
    op.create_table('background_tasks',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('phase', sa.String(length=80), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('parent_task_id', sa.String(length=36), nullable=True),
    sa.Column('checkpoint_version', sa.Integer(), nullable=False),
    sa.Column('checkpoint_json', sa.JSON(), nullable=True),
    sa.Column('error_summary', sa.String(length=500), nullable=True),
    sa.Column('lease_owner', sa.String(length=100), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_task_id'], ['background_tasks.task_id'], ),
    sa.PrimaryKeyConstraint('task_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('backups',
    sa.Column('backup_id', sa.String(length=36), nullable=False),
    sa.Column('archive_relative_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('backup_format_version', sa.String(length=20), nullable=False),
    sa.Column('schema_version', sa.String(length=100), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('total_size', sa.Integer(), nullable=False),
    sa.Column('manifest_sha256', sa.String(length=64), nullable=False),
    sa.Column('includes_vectors', sa.Boolean(), nullable=False),
    sa.Column('includes_parsed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_summary', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('backup_id')
    )
    op.create_table('content_objects',
    sa.Column('content_object_id', sa.String(length=36), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('detected_mime_type', sa.String(length=255), nullable=True),
    sa.Column('storage_relative_path', sa.String(length=500), nullable=False),
    sa.Column('storage_state', sa.String(length=30), nullable=False),
    sa.Column('reference_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('content_object_id'),
    sa.UniqueConstraint('sha256')
    )
    op.create_table('folders',
    sa.Column('folder_id', sa.String(length=36), nullable=False),
    sa.Column('parent_folder_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purge_after', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_folder_id'], ['folders.folder_id'], ),
    sa.PrimaryKeyConstraint('folder_id'),
    sa.UniqueConstraint('parent_folder_id', 'normalized_name', name='uq_folder_parent_name')
    )
    op.create_table('knowledge_bases',
    sa.Column('knowledge_base_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('active_index_version_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purge_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('knowledge_base_id')
    )
    op.create_table('provider_profiles',
    sa.Column('provider_profile_id', sa.String(length=36), nullable=False),
    sa.Column('provider_type', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('default_chat_model', sa.String(length=100), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('secret_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('provider_profile_id')
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('normalized_name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('normalized_name')
    )
    op.create_table('backup_entries',
    sa.Column('backup_entry_id', sa.String(length=36), nullable=False),
    sa.Column('backup_id', sa.String(length=36), nullable=False),
    sa.Column('relative_path', sa.String(length=500), nullable=False),
    sa.Column('entry_type', sa.String(length=30), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['backup_id'], ['backups.backup_id'], ),
    sa.PrimaryKeyConstraint('backup_entry_id')
    )
    op.create_table('files',
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('content_object_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.String(length=20), nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('folder_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('parse_revision_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purge_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_object_id'], ['content_objects.content_object_id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.folder_id'], ),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_table('task_attempts',
    sa.Column('task_attempt_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('checkpoint_version', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['background_tasks.task_id'], ),
    sa.PrimaryKeyConstraint('task_attempt_id')
    )
    op.create_table('task_events',
    sa.Column('task_event_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['background_tasks.task_id'], ),
    sa.PrimaryKeyConstraint('task_event_id')
    )
    op.create_table('file_tags',
    sa.Column('file_tag_id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.file_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], ),
    sa.PrimaryKeyConstraint('file_tag_id'),
    sa.UniqueConstraint('file_id', 'tag_id', name='uq_file_tag')
    )
    op.create_table('knowledge_base_files',
    sa.Column('knowledge_base_file_id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_base_id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('membership_status', sa.String(length=30), nullable=False),
    sa.Column('index_state', sa.String(length=30), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.file_id'], ),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.knowledge_base_id'], ),
    sa.PrimaryKeyConstraint('knowledge_base_file_id'),
    sa.UniqueConstraint('knowledge_base_id', 'file_id', name='uq_knowledge_base_file')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_base_files')
    op.drop_table('file_tags')
    op.drop_table('task_events')
    op.drop_table('task_attempts')
    op.drop_table('files')
    op.drop_table('backup_entries')
    op.drop_table('tags')
    op.drop_table('provider_profiles')
    op.drop_table('knowledge_bases')
    op.drop_table('folders')
    op.drop_table('content_objects')
    op.drop_table('backups')
    op.drop_table('background_tasks')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
